apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployments-app-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployments-app-web
  template:
    metadata:
      labels:
        app: deployments-app-web
    spec:
      containers:
        - name: app-web
          image: yuriihavrylko/prjctr:latest
