apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: kserve-custom
spec:
  predictor:
    minReplicas: 1
    containers:
      - name: kserve-container
        image: yuriihavrylko/app-kserve:latest

  transformer:
    minReplicas: 1
    containers:
      - image: yuriihavrylko/app-kserve-transformer:latest
        name: kserve-container
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi
---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
    - kafka-headless.default.svc.cluster.local:9092
  topics:
    - test
  sink:
    ref:
      apiVersion: serving.kserve.io/v1beta1
      kind: InferenceService
      name: kserve-custom
    uri: /v1/models/kserve-custom:predict
