apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: app-kserve
spec:
  predictor:
    containers:
      - name: kserve-container
        image: yuriihavrylko/app-kserve:latest

  