name: Deploy Image to Docker Hub

env:
  APP_NAME: 'prjctr'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}

      - name: 'Build & Push Image'
        run: |
          docker build . --tag docker.io/${{ secrets.DH_USERNAME }}/$APP_NAME:latest
          docker push docker.io/${{ secrets.DH_USERNAME }}/$APP_NAME:latest
